# Домашняя работа

## Easy

Открыть набор данных dota_hero_stats.csv из папки data. 

Данные взяты [отсюда](https://api.opendota.com/api/heroes), на этом же [сайте](https://www.opendota.com/) можно найти больше разнообразных данных по Dota2.

Пересчитаем число ног у героев игры Dota2! Сгруппируйте героев из датасэта по числу их ног (колонка legs), и посчитайте количество героев для каждого значения legs

## Normal

Продолжим исследование героев Dota2. Сгруппируйте по колонкам attack_type и primary_attr и выберите самый распространённый набор характеристик. Выведите список героев с этим набором характеристик


## Hard

В колонке roles находится список того, к каким ролям приписывают создатели Dota того или иного героя. 
Так же у каждого героя есть его основная характеристика, которая записана в колонке primary_attr.

1) Для каждой роли требуется построить bar plot на котором будет видно какое колличество раз героев с тем или иным основным атрибутам создатели игры относят к данной роли.

2) Так же требуется сделать обратный график: для каждого основного аттрибута сделайте bar plot на котором будет видно какое колличество раз создатели Dota относили героя с этим атрибутом к конкретной роли.

3) Сделайте выводы по полученым графикам (это могут быть совершенно любые выводы)

P.s
Для задания 1 должно получится 12 таких графиков (для каждой роли):

![screen 1](https://raw.githubusercontent.com/Shakirov-ER/brunoyam-ds-SC372-2560/main/images/02-screenshot_1.png)

Для задания 2 должно получится 3 таких графика (для каждого атрибута): 

![screen 2](https://raw.githubusercontent.com/Shakirov-ER/brunoyam-ds-SC372-2560/main/images/02-screenshot_2.png)

p.s.s Задание непростое. Попробуйте сначала сделать сами. Если не получается, то в ноутбуке 02-solution есть подсказка

# Решение Easy

In [283]:
import numpy as np
import pandas as pd
df = pd.read_json('heroes.json')
df

,id,name,localized_name,primary_attr,attack_type,roles,legs
0,1,npc_dota_hero_antimage,Anti-Mage,agi,Melee,"[Carry, Escape, Nuker]",2
1,2,npc_dota_hero_axe,Axe,str,Melee,"[Initiator, Durable, Disabler, Carry]",2
2,3,npc_dota_hero_bane,Bane,int,Ranged,"[Support, Disabler, Nuker, Durable]",4
3,4,npc_dota_hero_bloodseeker,Bloodseeker,agi,Melee,"[Carry, Disabler, Nuker, Initiator]",2
4,5,npc_dota_hero_crystal_maiden,Crystal Maiden,int,Ranged,"[Support, Disabler, Nuker]",2
...,...,...,...,...,...,...,...
119,129,npc_dota_hero_mars,Mars,str,Melee,"[Carry, Initiator, Disabler, Durable]",2
120,135,npc_dota_hero_dawnbreaker,Dawnbreaker,str,Melee,"[Carry, Durable]",2
121,136,npc_dota_hero_marci,Marci,str,Melee,"[Support, Carry, Initiator, Disabler, Escape]",2
122,137,npc_dota_hero_primal_beast,Primal Beast,str,Melee,"[Initiator, Durable, Disabler]",2
123,138,npc_dota_hero_muerta,Muerta,int,Ranged,"[Carry, Nuker, Disabler]",2

In [284]:
df[['localized_name', 'legs']] # группировка героев по числу ног

     localized_name  legs
0         Anti-Mage     2
1               Axe     2
2              Bane     4
3       Bloodseeker     2
4    Crystal Maiden     2
..              ...   ...
119            Mars     2
120     Dawnbreaker     2
121           Marci     2
122    Primal Beast     2
123          Muerta     2

[124 rows x 2 columns]

In [285]:
df['legs'].value_counts() # выявляем количество героев для каждого значения legs.

2    98
0    14
4     8
6     3
8     1
Name: legs, dtype: int64